version: 0.2
phases:
  install:
    commands:
      - cd services/reports/prtg
      - dotnet publish -c Release
      - aws cloudformation package --template-file template.yaml --s3-bucket reporterbotdeploymentbucket --output-template-file template-sam-prtg.yaml
      - aws cloudformation deploy --template-file template-sam-prtg.yaml --stack-name prtg-service --capabilities CAPABILITY_IAM
      - aws cloudformation describe-stacks --stack-name prtg-service --query 'Stacks[].Outputs'
      - echo $CODEBUILD_SRC_DIR
artifacts:
  type: zip
  files:
    - src/PRTG/bin/Release/netcoreapp2.1/publish/*
    - template.yaml
    - outputSamTemplate.yaml
# https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/