version: 0.2
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yaml --s3-bucket reporterbotdeploymentbucket --output-template-file template-sam-reporterbot.yaml
      - aws cloudformation deploy --template-file template-sam-reporterbot.yaml --stack-name reporterbot-sam-build --capabilities CAPABILITY_IAM
      - aws cloudformation describe-stacks --stack-name reporterbot-sam-build --query 'Stacks[].Outputs'
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml