version: 0.2
phases:
  install:
    commands:
      - dotnet publish -c Release
      - aws cloudformation package --template-file template.yaml --s3-bucket reporterbotdeploymentbucket --output-template-file template-sam-htmlbuilder.yaml
      - aws cloudformation deploy --template-file template-sam-htmlbuilder.yaml --stack-name htmlbuilder-service --capabilities CAPABILITY_IAM
      - aws cloudformation describe-stacks --stack-name htmlbuilder-service --query 'Stacks[].Outputs'
artifacts:
  type: zip
  files:
    - src/HelloWorld/bin/Release/netcoreapp2.1/publish/*
    - template.yaml
    - outputSamTemplate.yaml
# https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/